// Start Translation
const translations = {
  en: {
    home: "Home",
    login: "Login",
    english: "English",
    arabic: "Arabic",
    post: "Post Your Offer",
    freePost: "Free",
    cars: "Cars",
    trucks: "Trucks",
    equipment: "Equipment",
    buses: "Buses",
    spareParts: "Spare Parts",
    hyundai: "Hyundai",
    kia: "KIA",
    bmw: "BMW",
    nissan: "Nissan",
    toyota: "Toyota",
    mercedes: "Mercedes Benz",
    ford: "Ford",
    mitsu: "Mitsubishi",
    chevrolet: "Chevrolet",
    honda: "Honda",
    Peugeot: "Peugeot",
    Volkswagen: "Volkswagen",
    Opel: "Opel",
    Lexus: "Lexus",
    fiat: "Fiat",
    skoda: "Skoda",
    mazda: "Mazda",
    Daweo: "Daweo",
    Isuzu: "Isuzu",
    Audi: "Audi",
    chrysler: "Chrysler",
    lada: "Lada",
    porsche: "Porsche",
    seat: "Seat",
    volvo: "Volvo",
    renault: "Renault",
    landRover: "Land Rover",
    suzuki: "Suzuki",
    jeep: "Jeep",
    subaru: "Subaru",
    tesla: "Tesla",
    dodge: "Dodge",
    cadillac: "Cadillac",
    daihatsu: "Daihatsu",
    gmc: "GMC",
    miniCooper: "Mini Cooper",
    alfaRomeo: "Alfa Romeo",
    jaguar: "Jaguar",
    jmc: "JMC",
    iveco: "Iveco",
    geely: "Geely",
    chery: "Chery",
    mg: "MG",
    lamborgini: "Lamborgini",
    ssangyong: "Ssangyong",
    jac: "JAC",
    abarth: "Abarth",
    ac: "AC",
    hummer: "Hummer",
    byd: "BYD",
    infinity: "Infinity",
    acura: "Acura",
    aiaxm: "Aiaxm",
    alpina: "Alpina",
    bentley: "Bentley",
    changan: "Changan",
    kaiyi: "Kaiyi",
    cupra: "Cupra",
    citroen: "Citroen",
    brilliance: "Brilliance",
    sangyong: "Sang Yong",
    forthing: "Forthing",
    baic: "BAIC",
    bestune: "Bestune",
    datsun: "Datsun",
    ferrari: "Ferrari",
    proton: "Proton",
    maserati: "Maserati",
    haval: "Haval",
    jetour: "Jetour",
    dongfeng: "Dong Feng",
    ds: "DS",
    join: "Join Our Family",
    web: "3rbitek.com",
    Promotion:
      "Get Our Promotion And Become A Member ,Put Your Work Gallery In 3rbitek.com And Increase Your Profit and Clients",
    Gallery: "Member Work Gallery",
    details: "Full Details",
    text: "All Vehicles In One Place | New & Used Cars , Trucks , Buses , Vans , Trailer , Heavy Equipment and  SpareParts , Research & Compare Models , Find Local Dealers , Sell Your Car & More",
    contact: "Contact Us On",
    mail: "info@3rbitek.com",
    follow: "Follow Us On",
    copyright: " Copyright © 3rbitek.com All Rights Reserved",
    offerPage: "Post Your Offer Here",
    advertise: "What do you want to advertise ?",
    type: "Choose your offer type ?",
    sale: "For Sale",
    rent: "For Rent",
    saleCar: "Sale Your Car Easily",
    carBrand: "Choose Car Brand",
    inputSearch: "Search",
    rentCar:"Rent A Car",
  },
  ar: {
    home: "الرئيسية",
    login: "الدخول",
    english: "الإنجليزية",
    arabic: "العربية",
    search: "ما الذى تبحث عنه ؟",
    post: "أضف إعلانك",
    freePost: "مجانا",
    cars: "سيارات",
    trucks: "شاحنات",
    equipment: "معدات ثقيلة",
    buses: "باصات",
    spareParts: "قطع غيار",
    hyundai: "هيونداي",
    kia: "كيا",
    bmw: "بي ام دبليو",
    forthing: "فورثيتج",
    kaiyi: "كايى",
    nissan: "نيسسان",
    toyota: "تيوتا",
    mercedes: "مرسيدس بنز",
    ford: "فورد",
    mitsu: "ميتسوبيشي",
    chevrolet: "شيفروليه",
    jetour: "جيتور",
    baic: "بايك",
    cupra: "كوبرا",
    maserati: "مازيراتي",
    honda: "هوندا",
    Peugeot: "بيجو",
    ds: "دي اس",
    sangyong: "سانج يونج",
    Volkswagen: "فولكس فاجن",
    bestune: "بيستون",
    dongfeng: "دونج فينج",
    jmc: "جمسي",
    lamborgini: "لامبورجيني",
    Opel: "اوبل",
    Lexus: "لكزس",
    fiat: "فيات",
    skoda: "سكودا",
    ssangyong: "سسانيونج",
    byd: "بي واي دي",
    mg: "ام جي",
    mazda: "مازدا",
    Daweo: "دايو",
    infinity: "انفينيتي",
    haval: "هافال",
    jaguar: "جاكوار",
    Isuzu: "ايسوزو",
    Audi: "اودي",
    chrysler: "كريزلر",
    lada: "لادا",
    porsche: "بورش",
    seat: "سيات",
    volvo: "فولفو",
    renault: "رينو",
    landRover: "لاندروفر",
    suzuki: "سوزيكي",
    jeep: "جيب",
    subaru: "سوبارو",
    tesla: "تيسلا",
    dodge: "دودج",
    cadillac: "كاديلاك",
    daihatsu: "دايهتسو",
    gmc: "جمس",
    miniCooper: "ميني كوبر",
    alfaRomeo: "ألفاروميو",
    iveco: "أيفيكو",
    geely: "جيلي",
    chery: "شيري",
    ferrari: "فيراري",
    hummer: "هامر",
    jac: "جاك",
    abarth: "أبارث",
    ac: "أس",
    acura: "أكيرا",
    aiaxm: "اياكزم",
    alpina: "ألبينا",
    bentley: "بينتلي",
    brilliance: "بيريلينس",
    changan: "شنجن",
    citroen: "سيتروين",
    datsun: "داتسن",
    proton: "بروتن",
    join: "انضم لعائلتنا",
    web: "3rbitek.com",
    Promotion:
      "انضم إلينا واحصل علي الخصم , ضع معرض أعمالك عندنا وزد أرباحك وعملائك.",
    Gallery: "معرض صور عملائنا",
    details: "مزيد من المعلومات",
    text: "سوق السيارات وقطع الغيار |  موقع إلكتروني مختص في بيع وشراء وتأجير وطلب السيارات والشاحنات والمقطورات والمعدات الثقيلة و الباصات والفانات وقطع الغيار",
    contact: "للتواصل معنا",
    mail: "info@3rbitek.com",
    follow: "تابعونا علي",
    copyright: "جميع الحقوق محفوظة لموقع عربيتك © 2022",
    offerPage: "ضع إعلانك هنا",
    advertise: "ماذا تريد أن تعلن ؟",
    type: "اختر نوع الإعلان",
    sale: "للبيع",
    rent: "للإيجار",
    saleCar: "بيع سيارتك بسهولة",
    carBrand: "اختر نوع السيارة",
    inputSearch: "بحث",
    rentCar:"استإجر سيارة",
  },
};
const option = document.querySelectorAll("option");
const languageSelector = document.getElementById("select");
const englishBtn = document.getElementById("eng-btn");
const arabicBtn = document.getElementById("arb-btn");
const input = document.getElementById("input-search");
const h2 = document.getElementById("head-id");

// const h2Before = window.getComputedStyle(h2, "::before");
// const h2After = window.getComputedStyle(h2, "::after");
// Set English Language
englishBtn.addEventListener("click", (eo) => {
  setLanguage(eo.target.value);
  input.setAttribute("placeholder", "What are you looking for ?");

  // h2.style.setProperty("--afterOpacity", "0");
  localStorage.setItem("search", input.getAttribute("placeholder"));
  localStorage.setItem("lang", eo.target.value);
});
// Set Arabic Language
arabicBtn.addEventListener("click", (eo) => {
  setLanguage(eo.target.value);
  input.setAttribute("placeholder", "ما الذى تبحث عنه؟");

  // h2.style.setProperty("--beforeOpacity", "0");
  localStorage.setItem("search", input.getAttribute("placeholder"));
  localStorage.setItem("lang", eo.target.value);
});
onload = () => {
  setLanguage(localStorage.getItem("lang"));
  input.setAttribute("placeholder", localStorage.getItem("search"));
  console.log(localStorage.getItem("search"));
};
const setLanguage = (language) => {
  const elements = document.querySelectorAll("[data-trans]");
  elements.forEach((item) => {
    const translationKey = item.getAttribute("data-trans");
    item.textContent = translations[language][translationKey];
  });
  document.dir = language === "ar" ? "rtl" : "ltr";
};
// End Translation
